"use strict";
(function(){
    const getSupabase=()=>window.aprilsSupabase||window.AprilsSupabase||null;
    async function wait(){ if(getSupabase()) return getSupabase(); return new Promise(r=>{let n=0;const t=setInterval(()=>onst d=getSupabase();if(d||++n>100){clearInterval(t);r(d)}},100)}) }
    const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
    const slug=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80);
    async function getInventory(){const db=await wait();if(!db)return[];const r=await db.from("settings").select("id,setting_key,setting_value").like("setting_key","inventory_item_%");if(r.error)return[];const items=(r.data||[]).map(x=>{try{return{...JSON.parse(x.setting_value||"{}"),id:x.id,setting_key:x.setting_key}}catch(_){return null}}).filter(x=>x&&x.name&&x.active!==false);let collectionOrder=new Map();try{const o=await db.from("settings").select("setting_key,setting_value").like("setting_key","inventory_collection_order_%");if(!o.error)(o.data||[]).forEach(x=>collectionOrder.set(String(x.setting_key).replace(/^inventory_collection_order_/,""),Number(x.setting_value||9999)));}catch(_){}return items.sort((a,b)=>(collectionOrder.get(slug(a.collection||""))||9999)-(collectionOrder.get(slug(b.collection||""))||9999)||Number(a.display_order||9999)-Number(b.display_order||9999));}
    function renderShop(items){const grid=document.getElementById("shopInventory");if(!grid)return;grid.innerHTML=items.length?items.map(item=>`<article class="service-card shop-card">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.name)}" style="width:100%;height:260px;object-fit:cover;border-radius:8px;margin-bottom:12px">`:""}<h3>${esc(item.name)}</h3><p>${esc(item.collection||"")}</p><p>${esc(item.description||"")}</p><strong>GHS ${Number(item.price||0).toFixed(2)}</strong><p class="shop-availability">${Number(item.quantity||0)<=0?"Out of Stock":"Available to order"}</p><button class="button gold shop-add" data-id="${esc(item.id)}" ${Number(item.quantity||0)<=0?"disabled":""}>Add to Checkout</button></article>`).join(""):"<div class='empty'>No garments are currently available for purchase.</div>";grid.querySelectorAll(".shop-add").forEach(b=>b.onclick=()=>{const item=items.find(x=>String(x.id)===String(b.dataset.id));if(!item)return;const cart=JSON.parse(sessionStorage.getItem("aprils_cart")||"[]");const found=cart.find(x=>String(x.id)===String(item.id));if(found)found.quantity=Math.min(Number(item.quantity),Number(found.quantity)+1);else cart.push({id:item.id,name:item.name,price:Number(item.price||0),quantity:1,max:Number(item.quantity||0)});sessionStorage.setItem("aprils_cart",JSON.stringify(cart));window.location.href="checkout.html";});}
    async function setupShop(){const items=await getInventory();renderShop(items);}
    async function setupCheckout(){const db=await wait();const box=document.getElementById("checkoutCart");const form=document.getElementById("checkoutForm");if(!box||!form)return;const items=await getInventory();let cart=[];try{cart=JSON.parse(sessionStorage.getItem("aprils_cart")||"[]")}catch(_){};cart=cart.map(x=>{const live=items.find(i=>String(i.id)===String(x.id));return live?{...x,name:live.name,price:Number(live.price||0),max:Number(live.quantity||0),quantity:Math.min(Number(x.quantity||1),Number(live.quantity||0))}:null}).filter(Boolean);function render(){const total=cart.reduce((s,x)=>s+x.price*x.quantity,0);box.innerHTML=cart.length?`<table><thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${cart.map((x,i)=>`<tr><td>${esc(x.name)}</td><td><input type="number" min="1" max="${x.max}" value="${x.quantity}" data-cart-qty="${i}"></td><td>GHS ${x.price.toFixed(2)}</td><td>GHS ${(x.price*x.quantity).toFixed(2)}</td></tr>`).join("")}</tbody></table><p><strong>Total: GHS ${total.toFixed(2)}</strong></p>`:"<p>Your checkout is empty. Return to the Shop and add a garment.</p>";box.querySelectorAll("[data-cart-qty]").forEach(inp=>inp.onchange=()=>{const i=Number(inp.dataset.cartQty);cart[i].quantity=Math.max(1,Math.min(cart[i].max,Number(inp.value)||1));sessionStorage.setItem("aprils_cart",JSON.stringify(cart));render()});}
    render();form.addEventListener("submit",async e=>{e.preventDefault();if(!cart.length)return alert("Please add at least one garment.");if(!db)return alert("The checkout service is temporarily unavailable.");const fd=new FormData(form);const total=cart.reduce((s,x)=>s+x.price*x.quantity,0);const journey={checkout:true,items:cart.map(x=>({inventoryId:x.id,name:x.name,quantity:x.quantity,unitPrice:x.price,total:x.quantity*x.price})),total,paymentMethod:String(fd.get("paymentMethod")||"Payment confirmation by Aprils Signature"),paymentStatus:"pending",orderStatus:"under_review",deliveryDate:String(fd.get("deliveryDate")||""),deliveryTime:String(fd.get("deliveryTime")||""),submittedAt:new Date().toISOString()};const payload={full_name:String(fd.get("fullName")||"").trim(),phone:String(fd.get("phone")||"").trim(),whatsapp:String(fd.get("whatsapp")||"").trim(),location:String(fd.get("location")||"").trim(),email:String(fd.get("email")||"").trim(),service:cart.map(x=>x.name).join(", "),journey:JSON.stringify(journey)};if(!payload.full_name||!payload.phone||!payload.location)return alert("Please complete your name, phone and location.");const r=await db.from("quote_requests").insert([payload]);if(r.error){alert("Checkout could not be submitted. Please try again.");return}try{if(window.aprilsDispatchNotification)await window.aprilsDispatchNotification("quote_requests",r.data?.[0]?.id,payload)}catch(_){}sessionStorage.removeItem("aprils_cart");form.reset();box.innerHTML="<div class='form-message success' style='display:block'>Thank you. Your checkout order has been received. Aprils Signature will confirm payment and fulfilment.</div>";});}
    if(document.body.classList.contains("shop-page")) setupShop();
    if(document.body.classList.contains("checkout-page")) setupCheckout();
})();
