/* Aprils Signature — site-wide date/time presentation.
 * Date inputs retain ISO YYYY-MM-DD internally for HTML compatibility, while the
 * browser is instructed to use the British DD/MM/YYYY locale. Stored timestamps
 * are displayed as UTC/GMT wherever a visible date/time is generated by scripts.
 */
(function(){
  "use strict";
  document.documentElement.lang="en-GB";
  function apply(){
    document.querySelectorAll('input[type="date"]').forEach(i=>{
      i.lang="en-GB";
      i.title="Date format: DD/MM/YYYY";
      const l=i.closest(".form-group")?.querySelect"label");
      if(l&&!/DD\/MM\/YYYY/i.test(l.textContent))l.insertAdjacentText("beforeend"," (DD/MM/YYYY)");
    });
    document.querySelectorAll('input[type="time"]').forEach(i=>{
      i.title="Time is recorded/displayed in GMT";
      const l=i.closest(".form-group")?.querySelector("label");
      if(l&&!/GMT/i.test(l.textContent))l.insertAdjacentText("beforeend"," (GMT)");
    });
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",apply);else apply();
  new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});
})();
