(()=>{'use strict';
const CFG=window.APRILS_SUPABASE_CONFIG||{}; const sb=(window.supabase&&CFG.url&&CFG.publishableKey)?window.supabase.createClient(CFG.url,CFG.publishableKey):null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={view:'dashboard',records:[]}; const key='aprils_redeveloped_records_v1';
const loadLocal=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}; const saveLocal=a=>localStorage.setItem(key,JSON.stringify(a));
const toast=m=>{const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3000)};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
async function all(type){ if(sb){const {data,error}=await sb.from('settings').select('*').eq('setting_key',`admin_record_${type}`);if(!error)return(data||[]).map(x=>({...x.value,id:x.id,_remote:true}));}return loadLocal().filter(x=>x.type===type);}
async function put(type,value,id){const rec={id:id||uid(),type,value:{...value,id:id||uid(),updated_at:new Date().toISOString()},updated_at:new Date().toISOString()}; if(sb){const setting_key=`admin_record_${type}`; const setting_value=rec.value; const {error}=await sb.from('settings').upsert({setting_key,setting_value},{onConflict:'setting_key'}); /* fallback local on schema/constraint mismatch */ if(!error)return rec.value;} const a=loadLocal();const i=a.findIndex(x=>x.id===rec.id);if(i>=0)a[i]=rec;else a.push(rec);saveLocal(a);return rec.value;}
async function remove(type,id){const a=loadLocal().filter(x=>!(x.type===type&&x.id===id));saveLocal(a);toast('Record deleted');render();}
function actionBar(){return '<div class="toolbar"><button class="primary" data-action="save">Save</button><button class="secondary" data-action="clear">Clear</button><button class="secondary" data-action="refresh">Refresh</button><button class="secondary" data-action="generate-pdf">Generate PDF</button><button class="secondary" data-action="share-pdf">Share PDF</button><button class="secondary" data-action="print">Print</button></div>'}
function fields(type){const common='<div class="grid"><div><label>Name / Customer</label><input name="name" required></div><div><label>Reference / Number</label><input name="reference"></div><div><label>Status</label><input name="status"></div><div><label>Amount</label><input name="amount" type="number" step="0.01"></div></div><label>Description / Details</label><textarea name="details"></textarea>';
 if(type==='inventory')return '<div class="grid"><div><label>Type</label><select name="asset_type"><option>Business Inventory</option><option>Current Stock</option><option>Asset</option></select></div><div><label>Item</label><input name="name" required></div><div><label>Category</label><input name="category"></div><div><label>Quantity</label><input name="quantity" type="number"></div><div><label>Value</label><input name="amount" type="number" step="0.01"></div></div><label>Details</label><textarea name="details"></textarea>';
 if(type==='deliveryPickup')return '<div class="grid"><div><label>Saved Invoice</label><select id="savedInvoice"><option value="">Select saved invoice</option></select></div><div><label>Search Invoice</label><input id="invoiceSearch" placeholder="Name or invoice number"></div></div><div id="deliveryItems" class="table-wrap"></div>';
 if(type==='invoicePricing'||type==='invoices'||type==='usersInvoice')return common+'<label>Document Type</label><select name="document_type"><option>Invoice</option><option>Receipt</option></select><label>Attach Image URL</label><input name="image_url" placeholder="Optional image URL">';
 if(type==='maintenance')return '<div class="grid"><div><label>Website Mode</label><select name="mode"><option value="live">Live</option><option value="maintenance">Maintenance</option></select></div><div><label>Notice</label><input name="notice" placeholder="We will be back shortly"></div></div><label>Newsletter</label><textarea name="newsletter" placeholder="Write newsletter content"></textarea>';
 return common+'<label>Attach Image URL</label><input name="image_url" placeholder="Optional image URL">';}
async function render(){const type=state.view, list=await all(type); let title=document.querySelector(`button[data-view="${type}"]`)?.textContent||type;
 if(type==='dashboard'){ $('#view').innerHTML='<h1>Dashboard Overview</h1><div class="card"><p>This is the clean redevelopment admin runtime. All active admin logic is contained in this new application.</p></div>';return;}
 $('#view').innerHTML=`<h1>${esc(title)}</h1><div class="card"><form id="recordForm">${fields(type)}${actionBar()}</form></div><div class="card"><div class="toolbar"><input id="filter" placeholder="Search records by name, reference, status or details"><button class="secondary" data-action="share-pdf">Share PDF</button><button class="secondary" data-action="print">Print</button></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Name / Item</th><th>Reference</th><th>Status</th><th>Amount</th><th>Actions</th></tr></thead><tbody>${list.map((r,i)=>row(r,i,type)).join('')}</tbody></table></div></div>`;
 $('#recordForm').addEventListener('submit',async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.id=uid();v.created_at=new Date().toISOString();await put(type,v,v.id);toast('Saved');render();});
 $('#filter')?.addEventListener('input',e=>filterRows(e.target.value));
 $('#savedInvoice')&&populateInvoices(); $('#invoiceSearch')?.addEventListener('input',searchInvoice);
 bindActions();}
function row(r,i,type){return `<tr data-search="${esc(JSON.stringify(r).toLowerCase())}"><td>${i+1}</td><td>${esc(r.name)}</td><td>${esc(r.reference)}</td><td>${esc(r.status)}</td><td>${esc(r.amount)}</td><td><div class="actions"><button class="secondary" data-row="${esc(r.id)}" data-row-action="edit">Edit</button><button class="secondary" data-row="${esc(r.id)}" data-row-action="view">View Full Details</button><button class="secondary" data-row="${esc(r.id)}" data-row-action="pdf">Generate PDF</button><button class="secondary" data-row="${esc(r.id)}" data-row-action="share">Share PDF</button>${type==='usersInvoice'?'':`<button class="danger" data-row="${esc(r.id)}" data-row-action="delete">Delete</button>`}</div></td></tr>`}
function filterRows(q){q=q.toLowerCase();document.querySelectorAll('tbody tr').forEach(tr=>tr.style.display=tr.dataset.search.includes(q)?'':'none')}
async function recordById(type,id){return (await all(type)).find(x=>String(x.id)===String(id));}
async function pdfBlob(record,title){const node=document.createElement('div');node.style.cssText='width:794px;padding:36px;background:#fff;color:#111;font-family:Arial';node.innerHTML=`<h1>APRILS SIGNATURE</h1><h2>${esc(title)}</h2><hr>${Object.entries(record).filter(([k])=>!['id','image_url'].includes(k)).map(([k,v])=>`<p><strong>${esc(k.replaceAll('_',' '))}:</strong> ${esc(v)}</p>`).join('')}${record.image_url?`<img src="${esc(record.image_url)}" style="max-width:100%;max-height:420px">`:''}<p>Generated ${new Date().toLocaleString()}</p>`;document.body.append(node);try{if(!window.html2pdf)throw new Error('PDF engine unavailable');const blob=await window.html2pdf().set({margin:8,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4'}}).from(node).outputPdf('blob');if(!blob||blob.size<1000)throw new Error('Empty PDF');return blob;}finally{node.remove()}}
async function downloadOrShare(record,title,share){const blob=await pdfBlob(record,title);const file=new File([blob],title.replace(/[^a-z0-9]+/gi,'-')+'.pdf',{type:'application/pdf'});if(share&&navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title,files:[file]});return;}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);toast(share?'This device cannot share files directly; PDF downloaded.':'PDF generated');}
function printRecord(r,title){const w=window.open('','_blank');w.document.write(`<h1>APRILS SIGNATURE</h1><h2>${esc(title)}</h2>${Object.entries(r).map(([k,v])=>`<p><b>${esc(k)}:</b> ${esc(v)}</p>`).join('')}`);w.document.close();w.focus();w.print();}
async function bindActions(){document.querySelectorAll('[data-row-action]').forEach(b=>b.onclick=async()=>{const r=await recordById(state.view,b.dataset.row);if(!r)return toast('Record not found');const a=b.dataset.rowAction;if(a==='delete')return remove(state.view,r.id);if(a==='view'){alert(Object.entries(r).map(([k,v])=>`${k}: ${v}`).join('\n'));return;}if(a==='edit'){const f=$('#recordForm');Object.entries(r).forEach(([k,v])=>f.elements[k]&&(f.elements[k].value=v));return window.scrollTo({top:0,behavior:'smooth'});}try{if(a==='pdf')await downloadOrShare(r,`${state.view}-${r.reference||r.name||'document'}`,false);if(a==='share')await downloadOrShare(r,`${state.view}-${r.reference||r.name||'document'}`,true);}catch(e){toast(e.message||'Document action failed');}});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action;if(a==='clear')$('#recordForm')?.reset();if(a==='refresh')render();if(a==='print')window.print();if(a==='generate-pdf'||a==='share-pdf'){const r={title:document.querySelector('h1')?.textContent,generated:new Date().toISOString(),records:await all(state.view)};try{await downloadOrShare(r,state.view,a==='share-pdf')}catch(e){toast(e.message)}}});}
async function populateInvoices(){const s=$('#savedInvoice');const inv=[...(await all('invoices')),...(await all('invoicePricing'))];s.innerHTML='<option value="">Select saved invoice</option>'+inv.map(x=>`<option value="${esc(x.id)}">${esc(x.reference||x.name||x.id)}</option>`).join('');s.onchange=()=>showDelivery(inv.find(x=>x.id===s.value));}
function searchInvoice(e){all('invoices').then(a=>{const q=e.target.value.toLowerCase();const r=a.find(x=>JSON.stringify(x).toLowerCase().includes(q));if(r)showDelivery(r);});}
function showDelivery(r){const d=$('#deliveryItems');if(!d||!r)return;d.innerHTML=`<table><thead><tr><th>#</th><th>Items / Description</th><th>Details</th><th>Quantity</th></tr></thead><tbody><tr><td>1</td><td>${esc(r.name||'')}</td><td>${esc(r.details||'')}</td><td>${esc(r.quantity||'')}</td></tr></tbody></table>`}
// payment details are stored as one shareable settings record; the public endpoint resolves the exact key/token.
async function savePaymentDetails(details){const token=uid();const payload={...details,token,saved_at:new Date().toISOString()};localStorage.setItem('aprils_payment_'+token,JSON.stringify(payload));if(sb)await sb.from('settings').upsert({setting_key:'payment_share_'+token,setting_value:payload},{onConflict:'setting_key'});return new URL('../payment.html?ref='+encodeURIComponent(token),location.href).href}
window.AprilsAdmin={savePaymentDetails};
$('#collapse').onclick=()=>$('#sidebar').classList.toggle('collapsed');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render();});render();
})();