"use strict";
(function(){
    const db=()=>window.aprilsSupabase||window.AprilsSupabase||null;
    const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
    const slug=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80);
    async function rows(){const d=db();if(!d)return[];const r=await d.from("settings").select("id,setting_key,setting_value,updated_at");return r.error?[]:(r.data||[])}
    async function save(key,val){return window.safeSettingUpsert?window.safeSettingUpsert(key,JSON.stringify(val)):(async()=>{const d=db();const old=await d.from("settings").select("id").eq("setting_key",key).limit(1);if(old.data?.length)return d.from("settings").update({setting_value:JSON.stringify(val),updated_at:new Date().toISOString()}).eq("id",old.data[0].id);return d.from("settings").insert({setting_key:key,setting_value:JSON.stringify(val),updated_at:new Date().toISOString()})})()}
    async function getInventory(){return(await rows()).filter(r=>r.setting_key.startsWith("inventory_item_")).map(r=>{try{return{...JSON.parse(r.setting_value||"{}"),id:r.id,setting_key:r.setting_key}}catch(_){return null}}).filter(Boolean).sort((a,b)=>Number(a.display_order||9999)-Number(b.display_order||9999))}
    async function loadInventory(){const list=document.getElementById("inventoryList");if(!list)return;const items=await getInventory();list.innerHTML=items.length?`<table><thead><tr><th>Collection / Batch</th><th>Garment</th><th>Price</th><th>Qty</th><th>Public</th><th>Actions</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.collection)}</td><td>${esc(x.name)}</td><td>GHS ${Number(x.price||0).toFixed(2)}</td><td><strong>${Number(x.quantity||0)}</strong>${Number(x.quantity||0)<=0?" — Out of Stock":""}</td><td>${x.active!==false?"Yes":"No"}</td><td><button class="secondary" data-edit-inventory="${esc(x.id)}">Edit</button> <button class="danger" data-delete-inventory="${esc(x.id)}">Delete</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No inventory items have been added yet.</div>`;list.querySelectorAll("[data-edit-inventory]").forEach(b=>b.onclick=()=>{const x=items.find(i=>String(i.id)===String(b.dataset.editInventory));if(!x)return;inventoryFormFill(x)});list.querySelectorAll("[data-delete-inventory]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this inventory item?"))return;const d=db();const r=await d.from("settings").delete().eq("id",b.dataset.deleteInventory);if(r.error)return alert(r.error.message);await loadInventory()})}
    async function exportInventoryPdf(){
        const items=await getInventory(); const root=document.createElement("div");root.style.cssText="background:#fff;padding:24px;font-family:Arial,sans-serif;color:#222;width:190mm";root.innerHTML=`<h1>Aprils Signature</h1><h2>Inventory / Stock Report</h2><p>Elegance in Every Stitch</p><p>Generated: ${new Date().toLocaleString()}</p>`;const table=document.createElement("table");table.style.cssText="width:100%;border-collapse:collapse";table.innerHTML='<thead><tr><th style="border:1px solid #777;padding:7px">Collection / Batch</th><th style="border:1px solid #777;padding:7px">Garment</th><th style="border:1px solid #777;padding:7px">Price</th><th style="border:1px solid #777;padding:7px">Quantity</th><th style="border:1px solid #777;padding:7px">Availability</th></tr></thead><tbody>'+items.map(x=>`<tr><td style="border:1px solid #777;padding:7px">${esc(x.collection)}</td><td style="border:1px solid #777;padding:7px">${esc(x.name)}</td><td style="border:1px solid #777;padding:7px">GHS ${Number(x.price||0).toFixed(2)}</td><td style="border:1px solid #777;padding:7px">${Number(x.quantity||0)}</td><td style="border:1px solid #777;padding:7px">${Number(x.quantity||0)>0?"Available":"Out of Stock"}</td></tr>`).join('')+'</tbody>';root.appendChild(table);document.body.appendChild(root);try{if(!window.html2pdf){const script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';await new Promise(resolve=>{script.onload=resolve;script.onerror=resolve;document.head.appendChild(script)});}if(window.html2pdf){const filename=`Aprils-Signature-Inventory-${new Date().toISOString().slice(0,10)}.pdf`;const worker=window.html2pdf().set({margin:.35,filename,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'landscape'}}).from(root);if(navigator.share&&navigator.canShare){const blob=await worker.outputPdf('blob');const file=new File([blob],filename,{type:'application/pdf'});if(navigator.canShare({files:[file]})){await navigator.share({title:'Aprils Signature Inventory',text:'Inventory / Stock Report',files:[file]});return;}}await worker.save();}}finally{root.remove();}}
    function exportInventoryCsv(items){const header=['Collection / Batch','Garment','Price (GHS)','Quantity','Availability'];const csv=[header,...items.map(x=>[x.collection||'',x.name||'',Number(x.price||0).toFixed(2),Number(x.quantity||0),Number(x.quantity||0)>0?'Available':'Out of Stock'])].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Aprils-Signature-Inventory-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

    function inventoryFormFill(x){document.getElementById("inventoryId").value=x.id||"";document.getElementById("inventoryCollection").value=x.collection||"";document.getElementById("inventoryName").value=x.name||"";document.getElementById("inventoryPrice").value=x.price??"";document.getElementById("inventoryQuantity").value=x.quantity??0;document.getElementById("inventoryOrder").value=x.display_order??1;document.getElementById("inventoryDescription").value=x.description||"";document.getElementById("inventoryActive").checked=x.active!==false;document.getElementById("inventoryForm").scrollIntoView({behavior:"smooth"})}
    async function loadCheckoutOrders(){const list=document.getElementById("checkoutList");if(!list)return;const d=db();if(!d)return;const r=await d.from("quote_requests").select("*").order("created_at",{ascending:false});const orders=(r.data||[]).map(x=>{let j={};try{j=JSON.parse(x.journey||"{}")}catch(_){}return{...x,j}}).filter(x=>x.j.checkout);list.innerHTML=orders.length?`<table><thead><tr><th>Date</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${orders.map(x=>`<tr><td>${x.created_at?new Date(x.created_at).toLocaleString():""}</td><td>${esc(x.full_name)}<br>${esc(x.phone)}</td><td>${esc((x.j.items||[]).map(i=>i.name+" × "+i.quantity).join(", "))}</td><td>GHS ${Number(x.j.total||0).toFixed(2)}</td><td>${esc(x.j.paymentStatus||"pending")}</td><td>${esc(x.j.orderStatus||"under_review")}</td><td><button class="primary" data-checkout-paid="${esc(x.id)}">Mark Payment Received &amp; Deduct Stock</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No checkout orders have been received.</div>`;list.querySelectorAll("[data-checkout-paid]").forEach(b=>b.onclick=async()=>{const x=orders.find(o=>String(o.id)===String(b.dataset.checkoutPaid));if(!x)return;if(!confirm("Confirm payment received and deduct the purchased quantities from inventory?"))return;const d=db();for(const item of x.j.items||[]){const inv=await d.from("settings").select("id,setting_key,setting_value").eq("id",item.inventoryId).maybeSingle();if(!inv.data)continue;let v={};try{v=JSON.parse(inv.data.setting_value||"{}")}catch(_){};v.quantity=Math.max(0,Number(v.quantity||0)-Number(item.quantity||0));await d.from("settings").update({setting_value:JSON.stringify(v),updated_at:new Date().toISOString()}).eq("id",inv.data.id)}x.j.paymentStatus="paid";x.j.orderStatus="fully_paid";await d.from("quote_requests").update({journey:JSON.stringify(x.j)}).eq("id",x.id);await loadCheckoutOrders()})}
    async function syncInventoryFromPayment(invoiceNumber){const d=db();if(!d||!invoiceNumber)return;const key="inventory_deducted_invoice_"+slug(invoiceNumber);const old=await d.from("settings").select("id").eq("setting_key",key).limit(1);if(old.data?.length)return;const rec=await d.from("settings").select("setting_value").eq("setting_key","invoice_record_"+slug(invoiceNumber)).limit(1);if(!rec.data?.length)return;let invoice={};try{invoice=JSON.parse(rec.data[0].setting_value||"{}")}catch(_){};const invRows=await getInventory();for(const line of invoice.lines||[]){const item=invRows.find(i=>String(i.name).trim().toLowerCase()===String(line.description).trim().toLowerCase());if(!item)continue;const r=await d.from("settings").select("id,setting_value").eq("id",item.id).maybeSingle();if(!r.data)continue;let v={};try{v=JSON.parse(r.data.setting_value||"{}")}catch(_){};v.quantity=Math.max(0,Number(v.quantity||0)-Number(line.quantity||0));await d.from("settings").update({setting_value:JSON.stringify(v),updated_at:new Date().toISOString()}).eq("id",item.id)}await save(key,{invoiceNumber,deductedAt:new Date().toISOString()})}
    async function loadErrorLog(){const list=document.getElementById("errorLogList");if(!list)return;const rs=(await rows()).filter(r=>r.setting_key.startsWith("system_error_")).map(r=>{try{return{...JSON.parse(r.setting_value||"{}"),id:r.id}}catch(_){return null}}).filter(Boolean).sort((a,b)=>String(b.time).localeCompare(String(a.time)));list.innerHTML=rs.length?`<table><thead><tr><th>Time</th><th>Page</th><th>Error</th></tr></thead><tbody>${rs.map(x=>`<tr><td>${esc(x.time)}</td><td>${esc(x.page)}</td><td><pre style="white-space:pre-wrap">${esc(x.message)}</pre></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No logged system errors.</div>`}
    function setup(){
        let errorLock=false;
        window.addEventListener("error", async event=>{ if(errorLock||!db())return; errorLock=true; try{await save("system_error_"+Date.now()+"_"+Math.random().toString(36).slice(2,7),{time:new Date().toISOString(),page:location.pathname,message:event.error?.stack||event.message||"Unknown JavaScript error"})}catch(_){} finally{errorLock=false;} });
        window.addEventListener("unhandledrejection", async event=>{ if(errorLock||!db())return; errorLock=true; try{await save("system_error_"+Date.now()+"_"+Math.random().toString(36).slice(2,7),{time:new Date().toISOString(),page:location.pathname,message:event.reason?.stack||String(event.reason||"Unhandled promise rejection")})}catch(_){} finally{errorLock=false;} });
        const form=document.getElementById("inventoryForm");if(form&&!form.dataset.bound){form.dataset.bound="1";form.addEventListener("submit",async e=>{e.preventDefault();const id=document.getElementById("inventoryId").value.trim();const val={collection:document.getElementById("inventoryCollection").value.trim(),name:document.getElementById("inventoryName").value.trim(),price:Number(document.getElementById("inventoryPrice").value||0),quantity:Number(document.getElementById("inventoryQuantity").value||0),display_order:Number(document.getElementById("inventoryOrder").value||1),description:document.getElementById("inventoryDescription").value.trim(),active:document.getElementById("inventoryActive").checked,updatedAt:new Date().toISOString()};const key=id?(await db().from("settings").select("setting_key").eq("id",id).maybeSingle()).data?.setting_key:"inventory_item_"+slug(val.collection+"_"+val.name);const r=await save(key,val);if(r.error){alert(r.error.message);return}form.reset();document.getElementById("inventoryId").value="";document.getElementById("inventoryActive").checked=true;await loadInventory()})}
        document.getElementById("inventoryExport")?.addEventListener("click",async()=>exportInventoryCsv(await getInventory()));
        document.getElementById("inventorySharePdf")?.addEventListener("click",exportInventoryPdf);
        document.getElementById("inventoryCancel")?.addEventListener("click",()=>{form?.reset();document.getElementById("inventoryId").value="";document.getElementById("inventoryActive").checked=true});document.getElementById("refreshErrorLog")?.addEventListener("click",loadErrorLog);document.getElementById("clearErrorLog")?.addEventListener("click",async()=>{if(!confirm("Clear all system error log entries?"))return;const d=db();const rs=(await rows()).filter(r=>r.setting_key.startsWith("system_error_"));for(const r of rs)await d.from("settings").delete().eq("id",r.id);await loadErrorLog()});}
    window.loadInventory=loadInventory;window.loadCheckoutOrders=loadCheckoutOrders;window.loadErrorLog=loadErrorLog;window.syncInventoryFromPayment=syncInventoryFromPayment;window.setupCommerceAdmin=setup;setup();
})();
