"use strict";
(function(){
 const db=()=>window.aprilsSupabase||window.AprilsSupabase||null;
 const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
 const slug=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80);
 async function rows(){const d=db();if(!d)return[];const r=await d.from("settings").select("id,setting_key,setting_value,updated_at");if(r.error)throw r.error;return r.data||[]}
 async function save(key,val){if(window.safeSettingUpsert)return window.safeSettingUpsert(key,JSON.stringify(val));const d=db();if(!d)throw new Error("Supabase is unavailable");const old=await d.from("settings").select("id").eq("setting_key",key).limit(1);if(old.error)throw old.error;if(old.data?.length)return d.from("settings").update({setting_value:JSON.stringify(val),updated_at:new Date().toISOString()}).eq("id",old.data[0].id);return d.from("settings").insert({setting_key:key,setting_value:JSON.stringify(val),updated_at:new Date().toISOString()})}
 async function getInventory(){return(await rows()).filter(r=>String(r.setting_key||"").startsWith("inventory_item_")).map(r=>{try{return{...JSON.parse(r.setting_value||"{}"),id:r.id,setting_key:r.setting_key}}catch(_){return null}}).filter(x=>x&&x.name).sort((a,b)=>Number(a.display_order||9999)-Number(b.display_order||9999))}
 async function syncPublicShopInventory(items){try{await save("site_link_shop_inventory",items.map(x=>({id:x.id,name:x.name,collection:x.collection,price:Number(x.price||0),quantity:Number(x.quantity||0),description:x.description||"",active:x.active!==false,display_order:Number(x.display_order||9999),image:x.image||""})));}catch(e){console.warn("Public shop sync skipped:",e)}}
 function busy(btn,on,label){if(!btn)return;btn.disabled=on;if(on){btn.dataset.oldText=btn.textContent;btn.textContent=label||"Working…"}else{btn.textContent=btn.dataset.oldText||btn.textContent;delete btn.dataset.oldText}}
 async function renderShopPreview(){const box=document.getElementById("shopInventoryPreview");if(!box)return;try{const items=await getInventory();box.innerHTML=items.length?`<h4>Shop Items</h4><table><thead><tr><th>Image</th><th>Garment</th><th>Price</th><th>Qty</th><th>Public</th></tr></thead><tbody>${items.map(x=>`<tr><td>${x.image?`<img class="inventory-thumb" src="${esc(x.image)}" alt="">`:`—`}</td><td>${esc(x.name)}</td><td>GHS ${Number(x.price||0).toFixed(2)}</td><td>${Number(x.quantity||0)}</td><td>${x.active!==false?"Yes":"No"}</td></tr>`).join("")}</tbody></table>`:`<h4>Shop Items</h4><div class="empty">No inventory items have been added yet. Add garments in Inventory / Stock and they will appear here and on the public Shop.</div>`}catch(e){box.innerHTML=`<div class="empty">Shop items could not be loaded: ${esc(e.message)}</div>`}}
 async function loadInventory(){const list=document.getElementById("inventoryList");if(!list)return;try{const items=await getInventory();await syncPublicShopInventory(items);list.innerHTML=items.length?`<table><thead><tr><th>Image</th><th>Collection / Batch</th><th>Garment</th><th>Price</th><th>Qty</th><th>Public</th><th>Actions</th></tr></thead><tbody>${items.map(x=>`<tr><td>${x.image?`<img class="inventory-thumb" src="${esc(x.image)}" alt="">`:`—`}</td><td>${esc(x.collection)}</td><td>${esc(x.name)}</td><td>GHS ${Number(x.price||0).toFixed(2)}</td><td><strong>${Number(x.quantity||0)}</strong>${Number(x.quantity||0)<=0?" — Out of Stock":""}</td><td>${x.active!==false?"Yes":"No"}</td><td><button class="secondary" data-edit-inventory="${esc(x.id)}">Edit</button> <button class="danger" data-delete-inventory="${esc(x.id)}">Delete</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No inventory items have been added yet.</div>`;list.querySelectorAll("[data-edit-inventory]").forEach(b=>b.onclick=()=>{const x=items.find(i=>String(i.id)===String(b.dataset.editInventory));if(x)inventoryFormFill(x)});list.querySelectorAll("[data-delete-inventory]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this inventory item?"))return;const d=db();const r=await d.from("settings").delete().eq("id",b.dataset.deleteInventory);if(r.error){alert(r.error.message);return}await loadInventory();await renderShopPreview()});}catch(e){list.innerHTML=`<div class="empty">Inventory could not be loaded: ${esc(e.message)}</div>`}}
 function inventoryFormFill(x){document.getElementById("inventoryId").value=x.id||"";document.getElementById("inventoryCollection").value=x.collection||"";document.getElementById("inventoryName").value=x.name||"";document.getElementById("inventoryPrice").value=x.price??"";document.getElementById("inventoryQuantity").value=x.quantity??0;document.getElementById("inventoryOrder").value=x.display_order??1;document.getElementById("inventoryDescription").value=x.description||"";document.getElementById("inventoryActive").checked=x.active!==false;document.getElementById("inventoryForm").scrollIntoView({behavior:"smooth",block:"center"});document.getElementById("inventoryName")?.focus()}
 async function fileToDataUrl(file){if(!file)return "";if(file.size>3*1024*1024)throw new Error("Please choose an image smaller than 3 MB.");return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(file)})}
 async function loadCheckoutOrders(){const list=document.getElementById("checkoutList");if(!list)return;const d=db();if(!d)return;try{let r=await d.from("quote_requests").select("*");if(r.error)throw r.error;const orders=(r.data||[]).map(x=>{let j={};try{j=JSON.parse(x.journey||"{}")}catch(_){}return{...x,j}}).filter(x=>x.j.checkout);list.innerHTML=orders.length?`<table><thead><tr><th>Date</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${orders.map(x=>`<tr><td>${esc(x.created_at||x.updated_at||"")}</td><td>${esc(x.full_name)}<br>${esc(x.phone)}</td><td>${esc((x.j.items||[]).map(i=>i.name+" × "+i.quantity).join(", "))}</td><td>GHS ${Number(x.j.total||0).toFixed(2)}</td><td>${esc(x.j.paymentStatus||"pending")}</td><td>${esc(x.j.orderStatus||"under_review")}</td><td><button class="primary" data-checkout-paid="${esc(x.id)}">Mark Payment Received &amp; Deduct Stock</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No checkout orders have been received.</div>`;list.querySelectorAll("[data-checkout-paid]").forEach(b=>b.onclick=async()=>{const x=orders.find(o=>String(o.id)===String(b.dataset.checkoutPaid));if(!x)return;if(!confirm("Confirm payment received and deduct the purchased quantities from inventory?"))return;busy(b,true,"Processing…");try{for(const item of x.j.items||[]){const inv=await d.from("settings").select("id,setting_key,setting_value").eq("id",item.inventoryId).maybeSingle();if(!inv.data)continue;let v={};try{v=JSON.parse(inv.data.setting_value||"{}")}catch(_){}v.quantity=Math.max(0,Number(v.quantity||0)-Number(item.quantity||0));const u=await d.from("settings").update({setting_value:JSON.stringify(v),updated_at:new Date().toISOString()}).eq("id",inv.data.id);if(u.error)throw u.error}x.j.paymentStatus="paid";x.j.orderStatus="fully_paid";const u=await d.from("quote_requests").update({journey:JSON.stringify(x.j)}).eq("id",x.id);if(u.error)throw u.error;await loadCheckoutOrders();await loadInventory()}catch(e){alert(e.message)}finally{busy(b,false)}})}catch(e){list.innerHTML=`<div class="empty">Checkout orders could not be loaded: ${esc(e.message)}</div>`}}
 async function syncInventoryFromPayment(invoiceNumber){const d=db();if(!d||!invoiceNumber)return;const key="inventory_deducted_invoice_"+slug(invoiceNumber);const old=await d.from("settings").select("id").eq("setting_key",key).limit(1);if(old.data?.length)return;const rec=await d.from("settings").select("setting_value").eq("setting_key","invoice_record_"+slug(invoiceNumber)).limit(1);if(!rec.data?.length)return;let invoice={};try{invoice=JSON.parse(rec.data[0].setting_value||"{}")}catch(_){}const invRows=await getInventory();for(const line of invoice.lines||[]){const item=invRows.find(i=>String(i.name).trim().toLowerCase()===String(line.description).trim().toLowerCase());if(!item)continue;let v={...item};v.quantity=Math.max(0,Number(v.quantity||0)-Number(line.quantity||0));await d.from("settings").update({setting_value:JSON.stringify({...v,id:undefined,setting_key:undefined}),updated_at:new Date().toISOString()}).eq("id",item.id)}await save(key,{invoiceNumber,deductedAt:new Date().toISOString()});await loadInventory()}
 async function loadErrorLog(){const list=document.getElementById("errorLogList");if(!list)return;try{const rs=(await rows()).filter(r=>String(r.setting_key||"").startsWith("system_error_")).map(r=>{try{return{...JSON.parse(r.setting_value||"{}"),id:r.id}}catch(_){return null}}).filter(Boolean).sort((a,b)=>String(b.time).localeCompare(String(a.time)));list.innerHTML=rs.length?`<table><thead><tr><th>Time</th><th>Page</th><th>Error</th></tr></thead><tbody>${rs.map(x=>`<tr><td>${esc(x.time)}</td><td>${esc(x.page)}</td><td><pre style="white-space:pre-wrap">${esc(x.message)}</pre></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No logged system errors.</div>`}catch(e){list.innerHTML=`<div class="empty">Error log could not be loaded: ${esc(e.message)}</div>`}}
 function setup(){let errorLock=false;window.addEventListener("error",async event=>{if(errorLock||!db())return;errorLock=true;try{await save("system_error_"+Date.now()+"_"+Math.random().toString(36).slice(2,7),{time:new Date().toISOString(),page:location.pathname,message:event.error?.stack||event.message||"Unknown JavaScript error"})}catch(_){}finally{errorLock=false}});window.addEventListener("unhandledrejection",async event=>{if(errorLock||!db())return;errorLock=true;try{await save("system_error_"+Date.now()+"_"+Math.random().toString(36).slice(2,7),{time:new Date().toISOString(),page:location.pathname,message:event.reason?.stack||String(event.reason||"Unhandled promise rejection")})}catch(_){}finally{errorLock=false}});
  const form=document.getElementById("inventoryForm");
  if(form&&!form.dataset.bound){form.dataset.bound="1";form.addEventListener("submit",async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');busy(btn,true,"Saving…");try{const id=document.getElementById("inventoryId").value.trim();const file=document.getElementById("inventoryImage")?.files?.[0];let image=await fileToDataUrl(file);const val={collection:document.getElementById("inventoryCollection").value.trim(),name:document.getElementById("inventoryName").value.trim(),price:Number(document.getElementById("inventoryPrice").value||0),quantity:Number(document.getElementById("inventoryQuantity").value||0),display_order:Number(document.getElementById("inventoryOrder").value||1),description:document.getElementById("inventoryDescription").value.trim(),active:document.getElementById("inventoryActive").checked,updatedAt:new Date().toISOString()};if(!val.name)throw new Error("Enter a garment name.");if(!image&&id){const old=await db().from("settings").select("setting_value").eq("id",id).maybeSingle();if(old.data){try{image=JSON.parse(old.data.setting_value||"{}").image||""}catch(_){}}}val.image=image;let key="inventory_item_"+slug(val.collection+"_"+val.name);if(id){const old=await db().from("settings").select("setting_key").eq("id",id).maybeSingle();if(old.error)throw old.error;if(old.data?.setting_key)key=old.data.setting_key;const u=await db().from("settings").update({setting_value:JSON.stringify(val),updated_at:new Date().toISOString()}).eq("id",id);if(u.error)throw u.error}else{const r=await save(key,val);if(r.error)throw r.error}form.reset();document.getElementById("inventoryId").value="";document.getElementById("inventoryActive").checked=true;await loadInventory();await renderShopPreview();alert("Inventory item saved successfully.")}catch(e){alert("Inventory could not be saved: "+e.message)}finally{busy(btn,false)}})}
  document.getElementById("inventoryExport")?.addEventListener("click",async e=>{const b=e.currentTarget;busy(b,true,"Exporting…");try{exportInventoryCsv(await getInventory())}finally{busy(b,false)}});
  document.getElementById("inventorySharePdf")?.addEventListener("click",async e=>{const b=e.currentTarget;busy(b,true,"Preparing PDF…");try{await exportInventoryPdf()}finally{busy(b,false)}});
  document.getElementById("inventoryCancel")?.addEventListener("click",()=>{form?.reset();document.getElementById("inventoryId").value="";document.getElementById("inventoryActive").checked=true});
  document.getElementById("refreshErrorLog")?.addEventListener("click",async e=>{const b=e.currentTarget;busy(b,true,"Refreshing…");try{await loadErrorLog()}finally{busy(b,false)}});
  document.getElementById("clearErrorLog")?.addEventListener("click",async e=>{if(!confirm("Clear all system error log entries?"))return;const b=e.currentTarget;busy(b,true,"Clearing…");try{const d=db();const rs=(await rows()).filter(r=>String(r.setting_key||"").startsWith("system_error_"));for(const r of rs){const x=await d.from("settings").delete().eq("id",r.id);if(x.error)throw x.error}await loadErrorLog()}catch(err){alert(err.message)}finally{busy(b,false)}});
 }
 window.loadInventory=loadInventory;window.loadCheckoutOrders=loadCheckoutOrders;window.loadErrorLog=loadErrorLog;window.syncInventoryFromPayment=syncInventoryFromPayment;window.renderShopPreview=renderShopPreview;window.setupCommerceAdmin=setup;setup();
})();